const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;

const API_URL = {
  base: baseUrl,

  machine: {
    listing: 'machines',
    add: 'machines',
    update: 'machines',
    getbyid: 'machines',
    export: 'machines/export',
  },

  machineShop: {
    listing: 'machine-shops',
    add: 'machine-shops',
    update: 'machine-shops',
    getbyid: 'machine-shops',
    import: 'machine-shops/import',
    export: 'machine-shops/export',
  },
  lineList: {
    listing: 'lines',
    add: 'lines',
    update: 'lines',
    getbyid: 'lines',
    import: 'lines/import',
    export: 'lines/export',
  },
  cell: {
    listing: 'cells',
    add: 'cells',
    update: 'cells',
    getbyid: 'cells',
    delete: 'cells',
    export: 'cells/export',
  },

  maincategories: {
    listing: 'machine-main-categories',
    add: 'machine-main-categories',
    update: 'machine-main-categories',
    getbyid: 'machine-main-categories',
    export: 'machine-main-categories/export',
  },
  managesubcategory: {
    listing: 'machine-sub-categories',
    add: 'machine-sub-categories',
    update: 'machine-sub-categories',
    getbyid: 'machine-sub-categories',
    export: 'machine-sub-categories/export',
  },
  manageworkcenter: {
    listing: 'work-centers',
    add: 'work-centers',
    update: 'work-centers',
    getbyid: 'work-centers',
    import: 'work-centers/import',
    export: 'work-centers/export',
  },
  machineMake: {
    listing: 'machine-makes',
    add: 'machine-makes',
    update: 'machine-makes',
    getbyid: 'machine-makes',
    export: 'machine-makes/export',
  },
  manageMakeMachine: {
    listing: 'MachineMakes/GetMachineMakes',
    add: '',
    update: '',
    getbyid: '',
  },
  dispatchTo: {
    listing: 'dispatch-tos',
    add: 'dispatch-tos',
    update: 'dispatch-tos',
    getbyid: 'dispatch-tos',
    export: 'dispatch-tos/export',
  },
  downTimeReason: {
    listing: 'downtime-category-reasons',
    add: 'downtime-category-reasons',
    update: 'downtime-category-reasons',
    getbyid: 'downtime-category-reasons',
    import: 'downtime-category-reasons/import',
    export: 'downtime-category-reasons/export',
  },
  workCenterdownTimeReason: {
    listing: 'work-centers/downtime-reasons',
    add: 'work-centers/downtime-reasons',
    update: 'work-centers/downtime-reasons',
    getbyid: 'work-centers/downtime-reasons',
    export: 'work-centers/downtime-reasons/export',
  },

  downTimeCategory: {
    listing: 'downtime-categories',
    add: 'downtime-categories',
    update: 'downtime-categories',
    getbyid: 'downtime-categories',
    export: 'downtime-categories/export',
  },
  unPlannedprdReasons: {
    listing: 'unplanned-production-reasons',
    add: 'unplanned-production-reasons',
    update: 'unplanned-production-reasons',
    getbyid: 'unplanned-production-reasons',
    export: 'unplanned-production-reasons/export',
  },
  drivers: {
    listing: 'drivers',
    add: 'drivers',
    update: 'drivers',
    getbyid: 'drivers',
    export: 'drivers/export',
  },
  vehicles: {
    listing: 'vehicles',
    add: 'vehicles',
    update: 'vehicles',
    getbyid: 'vehicles',
    import: 'vehicles/import',
    export: 'vehicles/export',
  },
  interMediateProcesses: {
    listing: 'intermediate-processes',
    add: 'intermediate-processes',
    update: 'intermediate-processes',
    getbyid: 'intermediate-processes',
    export: 'intermediate-processes/export',
  },
  materialsCode: {
    listing: 'materials',
    add: 'materials',
    update: 'materials',
    getbyid: 'materials',
    export: 'materials/export',
  },
  preProcesses: {
    listing: 'pre-processes',
    add: 'pre-processes',
    update: 'pre-processes',
    getbyid: 'pre-processes',
    export: 'pre-processes/export',
  },
  preFunctions: {
    listing: 'pre-functions',
    add: 'pre-functions',
    update: 'pre-functions',
    getbyid: 'pre-functions',
    export: 'pre-functions/export',
  },
  supervisoursGroup: {
    listing: 'supervisor-groups',
    add: 'supervisor-groups',
    update: 'supervisor-groups',
    getbyid: 'supervisor-groups',
    export: 'supervisor-groups/export',
  },
  asstManagerMaster: {
    listing: 'employees',
    add: 'employees',
    update: 'employees',
    getbyid: 'employees',
    export: 'employees/export',
  },
  controllerMaster: {
    listing: 'machine-controllers',
    add: 'machine-controllers',
    update: 'machine-controllers',
    getbyid: 'machine-controllers',
    import: 'machine-controllers/import',
    export: 'machine-controllers/export',
  },
  shiftmaster: {
    listing: 'Shifts/GetShifts',
    add: '',
    update: '',
    getbyid: '',
  },
  documentTypeMaster: {
    listing: 'document-types',
    add: 'document-types',
    update: 'document-types',
    getbyid: 'document-types',
    export: 'document-types/export',
  },
  holidays: {
    listing: 'holidays',
    add: 'holidays',
    update: 'holidays',
    getbyid: 'holidays',
    import: 'holidays/import',
    export: 'holidays/export',
  },
  manageMachine: {
    listing: 'machines',
    add: 'machines',
    update: 'machines',
    getbyid: 'machines',
    import: 'machines/import',
    export: 'machines/export',
  },
  palletMaster: {
    listing: 'pallets',
    add: 'pallets',
    update: 'pallets',
    getbyid: 'pallets',
    export: 'pallets/export',
  },

  unitList: {
    listing: 'units',
    add: 'units',
    update: 'units',
    getbyid: 'units',
    import: 'units/import',
    export: 'units/export',
  },
  machineShopOf: {
    listing: 'machine-shop-ofs',
    add: 'machine-shop-ofs',
    update: 'machine-shop-ofs',
    getbyid: 'machine-shop-ofs',
    export: 'machine-shop-ofs/export',
  },
  weekoff: {
    listing: 'week-off',
    add: 'week-off',
    update: 'week-off',
    getbyid: 'week-off',
    export: 'week-off/export',
  },

  breakManagement: {
    listing: 'break-with-work-center-management/GetBreakWithWorkCenter',
    add: '',
    update: '',
    getbyid: '',
  },

  shiftManagement: {
    listing: 'shifts',
    add: 'shifts',
    update: 'shifts',
    getbyid: 'shifts',
    export: 'shifts/export',
  },
  specialWorking: {
    listing: 'special-working-days',
    add: 'special-working-days',
    update: 'special-working-days',
    getbyid: 'special-working-days',
    search: 'special-working-days/GetHolidaysAndWeekofs',
    export: 'special-working-days/export',
  },
  employees: {
    listing: 'employees',
    add: 'employees',
    update: 'employees',
    getbyid: 'employees',
    import: 'employees/import',
    export: 'employees/export',
  },

  breakWithWorkCenterManagement: {
    listing: 'break-with-work-center-management/GetBreakWithWorkCenter',
    add: '',
    update: '',
    getbyid: '',
  },
  breakWithShiftManagement: {
    listing: 'breaks',
    add: 'breaks',
    update: 'breaks',
    getbyid: 'breaks',
    export: 'breaks/export',
  },
  dailyProductionMail: {
    listing: 'daily-production-mail-logs',
    add: 'daily-production-mail-logs',
    update: 'daily-production-mail-logs',
    getbyid: 'daily-production-mail-logs',
    export: 'daily-production-mail-logs/export',
  },
  common: {
    listing: 'common',
  },
  hmiBadgeList: {
    listing: 'HMIBadge',
    add: 'HMIBadge',
    update: 'HMIBadge',
    getbyid: 'HMIBadge',
    export: 'HMIBadge/export',
  },
  badgeDocument: {
    listing: 'badge-documents',
    add: 'badge-documents',
    update: 'badge-documents',
    getbyid: 'badge-documents',
    file: 'badge-documents/File',
    export: 'badge-documents/export',
  },
  planningLogs: {
    listing: 'planning-logs',
    add: 'planning-logs',
    update: 'planning-logs',
    getbyid: 'planning-logs',
    export: 'planning-logs/export',
  },
  workType: {
    listing: 'work-center-types',
    add: 'work-center-types',
    update: 'work-center-types',
    getbyid: 'work-center-types',
    export: 'work-center-types/export',
  },
  workcentergroups: {
    listing: 'work-center-groups',
    add: 'work-center-groups',
    update: 'work-center-groups',
    getbyid: 'work-center-groups',
    export: 'work-center-groups/export',
  },
  machineparts: {
    listing: 'machine-parts',
    add: 'machine-parts',
    update: 'machine-parts',
    getbyid: 'machine-parts',
    expand: 'machine-parts/operations',
    import: 'machine-parts/import',
    export: 'machine-parts/export',
  },
  productionOrder: {
    listing: 'production-orders',
    add: 'production-orders',
    import: 'production-orders/import',
    update: 'production-orders',
    getbyid: 'production-orders',
    expand: 'production-orders',
    statusUpdate: 'production-orders/update-status',
    split: 'production-orders/split',
    export: 'production-orders/export',
  },
  shopPlanning: {
    listing: 'production-planning',
    add: 'production-planning/import',
    update: 'production-planning',
    getbyid: 'production-planning',
    expand: 'production-planning',
  },
  commonSwitch: {
    update: 'common/update-status',
  },
  batchTimeScheduling: {
    listing: 'batch-time-scheduling',
    update: 'batch-time-scheduling',
    getbyid: 'batch-time-scheduling',
    schedulers: 'schedulers',
  },
  schedulingPlayground: {
    update: 'scheduling-playground',
  },
  WorkCenterOperator: {
    listing: 'work-center-operator',
    add: 'work-center-operator',
    update: 'work-center-operator',
    getbyid: 'work-center-operator',
    expand: 'work-center-operator',
  },
  additionalShift: {
    listing: 'additional-shifts',
    add: 'additional-shifts',
    update: 'additional-shifts',
    getbyid: 'additional-shifts',
  },
  hmi: {
    listing: 'hmi/productions',
    productionsDetails: 'hmi/operation-queues',
    receivedqty:'hmi/received-qty',
    allocations : 'work-centers/allocations',
    downtimes: 'work-centers/down-times',
    addDowntime: 'hmi/down-work-center',
    remarks: 'production-orders/lots/remarks',
  },
};

export default API_URL;
